---
- hosts: all
  vars:
    vm_name: STUDENTXX_Ansible_demo_vm
  tasks:
    - name: 'Simplivity clone'
      simplivity_virtual_machine:
        ovc_ip: 16.31.87.107
        username: root
        password: vmware
        state: clone
        data:
          name: '{{ vm_name }}'
          new_name: '{{ vm_name}}_clone'
      delegate_to: localhost



